# Generated by Django 2.2.12 on 2022-09-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.IntegerField(default=0)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Departments')),
            ],
        ),
    ]
